/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.robotics.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RigidBodiesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("uk/ac/kcl/inf/robotics/parser/antlr/internal/InternalRigidBodies.tokens");
	}
}
