/**
 * generated by Xtext
 */
package uk.ac.kcl.inf.robotics.ui.contentassist;

import uk.ac.kcl.inf.robotics.ui.contentassist.AbstractRigidBodiesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RigidBodiesProposalProvider extends AbstractRigidBodiesProposalProvider {
}
