/*
 * generated by Xtext
 */
package uk.ac.kcl.inf.robotics;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RigidBodiesStandaloneSetup extends RigidBodiesStandaloneSetupGenerated{

	public static void doSetup() {
		new RigidBodiesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

